title: "Stig's Blog"
author: "Stig Schmidt Nielsson"
description: "Stig Schmidt Nielsson's blog mainly about software engineering using C# and .Net"

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
#email: "stig@mail.com"
twitter_username: "snielsson"
github_username: "snielsson"
linkedin_username: "snielsson"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

excerpt_separator   : "\n\n"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable : true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - premonition  

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
